"""cron-pipe CLI — ``cron-pipe init`` generates writer/reader boilerplate."""

import argparse
import os
import sys
from pathlib import Path

from . import __version__

_STATE_PATH_PLACEHOLDER = "__CRON_PIPE_STATE_PATH__"
_THRESHOLD_PLACEHOLDER = "__CRON_PIPE_THRESHOLD__"

WRITER_TPL = r'''#!/usr/bin/env python3
"""Writer — evaluates conditions, writes state for downstream readers.

Generated by ``cron-pipe init``. Replace ``evaluate()`` with your logic.
"""
import sys
from pathlib import Path
from cron_pipe import StateWriter

STATE_FILE = str(Path.home() / "__CRON_PIPE_STATE_PATH__")


def evaluate() -> dict:
    """Your condition logic here. Keep it light (no LLM, no heavy APIs).

    Returns a dict with at least "action": "PROCEED" or "HALT".
    Include "score" (float) if you plan to use threshold gating.
    """
    # --- Replace below with your logic ---
    # Example: check if it's a specific time window
    import datetime
    now = datetime.datetime.now()
    is_active = 9 <= now.hour <= 15
    return {
        "action": "PROCEED" if is_active else "HALT",
        "score": 0.8 if is_active else 0.0,
    }


def main():
    result = evaluate()
    with StateWriter(STATE_FILE) as w:
        action = result.get("action", "HALT")
        if action == "PROCEED":
            w.proceed(score=result.get("score"))
        else:
            w.halt(reason=result.get("reason", "condition not met"))
    print(f"[writer] wrote action={action}", file=sys.stderr)


if __name__ == "__main__":
    main()
'''

READER_TPL = r'''#!/usr/bin/env python3
"""Reader — gates execution based on state from upstream writer.

Generated by ``cron-pipe init``. The gate is at the top so we
exit before loading any heavy dependencies.
"""
import sys
from pathlib import Path
from cron_pipe import StateGate

STATE_FILE = str(Path.home() / "__CRON_PIPE_STATE_PATH__")


def main():
    gate = StateGate(STATE_FILE)

    # --- Gate ----------------------------------------------------------
    # Exits silently (exit 0) when conditions aren't met.
    gate.require_proceed(__CRON_PIPE_THRESHOLD__)

    # --- Heavy logic below ---------------------------------------------
    print("Gate passed -- running expensive logic")
    # TODO: replace with your actual workload


if __name__ == "__main__":
    main()
'''


def cmd_init(args):
    """Handle ``cron-pipe init``."""
    state_path = args.state_path or "data/cron_pipe_state.json"
    threshold_str = f"threshold={args.threshold}" if args.threshold else ""

    writer_path = Path(args.writer)
    reader_path = Path(args.reader)

    writer_path.parent.mkdir(parents=True, exist_ok=True)
    reader_path.parent.mkdir(parents=True, exist_ok=True)

    writer_content = WRITER_TPL.replace(_STATE_PATH_PLACEHOLDER, state_path)
    reader_content = READER_TPL.replace(_STATE_PATH_PLACEHOLDER, state_path)
    reader_content = reader_content.replace(_THRESHOLD_PLACEHOLDER, threshold_str)

    writer_path.write_text(writer_content)
    reader_path.write_text(reader_content)

    os.chmod(writer_path, 0o755)
    os.chmod(reader_path, 0o755)

    print(f"  \u2705  {writer_path}")
    print(f"  \u2705  {reader_path}")
    print()
    print(f"  State file:  ~/{state_path}")
    if args.threshold:
        print(f"  Threshold:   {args.threshold}")
    print()
    print("  Next steps:")
    print(f"    1. Edit {writer_path.name} -- replace evaluate()")
    print(f"    2. Edit {reader_path.name} -- replace heavy logic")
    print("    3. Schedule in crontab:")
    cwd = Path.cwd()
    print(f"        * * * * * cd {cwd} && python {writer_path.name}")
    print(f"        * * * * * cd {cwd} && python {reader_path.name}")
    print()


def main():
    parser = argparse.ArgumentParser(
        prog="cron-pipe",
        description="Turn dumb cron jobs into state-aware, conditional pipelines.",
    )
    parser.add_argument(
        "--version", action="version",
        version=f"cron-pipe {__version__}",
    )

    sub = parser.add_subparsers(dest="command")

    init = sub.add_parser("init", help="Generate writer/reader boilerplate")
    init.add_argument(
        "--writer", default="writer.py",
        help="Output path for the writer script [writer.py]",
    )
    init.add_argument(
        "--reader", default="reader.py",
        help="Output path for the reader script [reader.py]",
    )
    init.add_argument(
        "--state-path", default="data/cron_pipe_state.json",
        help="State file path under $HOME [data/cron_pipe_state.json]",
    )
    init.add_argument(
        "--threshold", type=float,
        help="Default score threshold. Omit to skip numerical gating.",
    )

    if len(sys.argv) < 2:
        parser.print_help()
        sys.exit(1)

    args = parser.parse_args()

    if args.command == "init":
        cmd_init(args)
    else:
        parser.print_help()
        sys.exit(1)


if __name__ == "__main__":
    main()
